POST http://localhost:8080/events
content-Type: application/json

{
	"name"   : "Test 2 Event"  , 
	"description" : "A test EVent",
	"location" : "A test Location",
	"dateTime": "2025-01-01T15:30:00.000Z" 
}
