DELETE http://localhost:8080/events/9
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpheTIzQGdtYWlsLmNvbSIsImV4cCI6MTcwODI0MzIwNiwidXNlcklEIjozfQ.ZDmUdTvuc_gfTPHeZZLnUnEKZ4KezLFDcbwT4ftGRtg