DELETE http://localhost:8080/events/8
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpheTFAZ21haWwuY29tIiwiZXhwIjoxNzA4MTEzNTM4LCJ1c2VySUQiOjJ9.6kwnWlZq1a4i-LdOOKoZkTM3kyAOTDKKjHpPl44RwSI
